spring:
  application:
    name: SpringData_I
  datasource:
    password: SpringDataApp
    url: jdbc:postgresql://postgresql-77265-0.cloudclusters.net:16651/springdata
    username: hasim
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080